# Generated by Django 5.0.6 on 2024-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
